In [33]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import joblib
import datetime
from sklearn.metrics import mean_squared_error, make_scorer, r2_score, accuracy_score, log_loss, confusion_matrix

In [34]:
random_state = 1
tf.random.set_seed(random_state)
np.random.seed(random_state)

In [35]:
model = tf.keras.models.load_model('/content/drive/MyDrive/WR2 Brrr/Trainingsdaten_Proj3/trained_model2')

In [36]:
data_list = []

for i in range(3):
  data_list.append(pd.read_csv('/content/drive/MyDrive/WR2 Brrr/Testdaten_Proj3/test_data_' + str(i+1) + '_dump.csv', header = None))
  print(data_list[i].shape)

(24, 4801)
(24, 4801)
(24, 4801)


In [37]:
model.summary()

Model: "sequential_3"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_1 (Dense)             (None, 800)               3840800   
                                                                 
 dropout_1 (Dropout)         (None, 800)               0         
                                                                 
 dense_2 (Dense)             (None, 800)               640800    
                                                                 
 dropout_2 (Dropout)         (None, 800)               0         
                                                                 
 dense_3 (Dense)             (None, 800)               640800    
                                                                 
 dropout_3 (Dropout)         (None, 800)               0         
                                                                 
 dense_4 (Dense)             (None, 800)              

In [47]:
i = 0 #waehle bild
X = data_list[i].iloc[:,:-1].values.astype('float32')
y_true = data_list[i].iloc[:,-1].values.astype('float32')
y_pred = model.predict(X)
print(y_pred)
y_pred_np = np.array([1 if prob > 0.45 else 0 for prob in y_pred]).astype('int64')
print(y_pred_np)
# Save predicted labels
file_name = '/content/drive/MyDrive/WR2 Brrr/Testdaten_Proj3/predicted_labels_' + str(i+1) + '.csv'
np.savetxt(file_name, y_pred_np, delimiter=",")

[[5.4284032e-05]
 [8.6261678e-01]
 [5.4284032e-05]
 [8.6261678e-01]
 [5.4284032e-05]
 [8.6261678e-01]
 [8.6261678e-01]
 [1.8090010e-04]
 [9.9729556e-01]
 [1.8090010e-04]
 [9.9729556e-01]
 [1.8090010e-04]
 [9.9729556e-01]
 [9.9729556e-01]
 [1.8090010e-04]
 [7.5133026e-01]
 [1.8090010e-04]
 [7.5133026e-01]
 [1.8090010e-04]
 [7.5133026e-01]
 [7.5133026e-01]
 [6.1026162e-06]
 [6.1026162e-06]
 [6.1026162e-06]]
[0 1 0 1 0 1 1 0 1 0 1 0 1 1 0 1 0 1 0 1 1 0 0 0]


[0 1 0 1 0 1 1 0 1 0 1 0 1 1 0 1 0 1 0 1 1 0 0 0]
