In [1]:
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
import tensorflow as tf
import joblib
import datetime
from sklearn.metrics import mean_squared_error, make_scorer, r2_score, accuracy_score, log_loss, confusion_matrix

In [2]:
random_state = 1
tf.random.set_seed(random_state)
np.random.seed(random_state)

In [3]:
model = tf.keras.models.load_model('/content/drive/MyDrive/WR2 Brrr/Trainingsdaten_Proj3/trained_model')

In [4]:
data_list = []

for i in range(3):
  data_list.append(pd.read_csv('/content/drive/MyDrive/WR2 Brrr/Testdaten_Proj3/test_data_' + str(i+1) + '_dump.csv', header = None))
  print(data_list[i].shape)

(24, 4801)
(24, 4801)
(24, 4801)


In [34]:
i = 0 #waehle bild
X = data_list[i].iloc[:,:-1].values.astype('float32')
y_true = data_list[i].iloc[:,-1].values.astype('float32')
y_pred = model.predict(X)
print(y_pred)

[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]]


In [5]:
for value in y_pred:
  print(value[0])

NameError: ignored

In [6]:
# label_list = []

# for i in range(3):
#   X = data_list[i].iloc[:,:-1]
#   y_true = data_list[i].iloc[:,-1]
#   y_pred = model.predict(X)
#   print(y_pred)

[[0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [1.]
 [0.]
 [0.]
 [0.]]
[[1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [1.]
 [0.]
 [1.]
 [0.]
 [0.]
 [0.]
 [0.]
 [1.]
 [1.]
 [1.]]
[[0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]
 [0.]]


In [8]:
model.summary()

Model: "sequential_2"
_________________________________________________________________
 Layer (type)                Output Shape              Param #   
 dense_12 (Dense)            (None, 500)               2400500   
                                                                 
 dropout_10 (Dropout)        (None, 500)               0         
                                                                 
 dense_13 (Dense)            (None, 500)               250500    
                                                                 
 dropout_11 (Dropout)        (None, 500)               0         
                                                                 
 dense_14 (Dense)            (None, 500)               250500    
                                                                 
 dropout_12 (Dropout)        (None, 500)               0         
                                                                 
 dense_15 (Dense)            (None, 500)              

In [36]:
print(model.outputs[0].dtype)

<dtype: 'float32'>


In [ ]:
model.layers()

In [18]:
model.layers[0].weights

[<tf.Variable 'dense_12/kernel:0' shape=(4800, 500) dtype=float32, numpy=
 array([[-2.4703193e-02,  2.7142856e-02,  1.4684651e-02, ...,
         -4.1186016e-05,  2.9486051e-02, -1.8233040e-02],
        [-2.8239477e-02, -2.2958085e-02,  1.3321964e-02, ...,
         -2.7392162e-02, -2.5649872e-02, -1.5071959e-02],
        [ 2.1623777e-02, -7.6690302e-03, -6.3008340e-03, ...,
          1.2698106e-02,  1.7477987e-02, -3.0532114e-02],
        ...,
        [-1.6455652e-02, -2.2584131e-02,  9.2723481e-03, ...,
          4.7797123e-03, -2.8841026e-02,  7.5011239e-03],
        [ 3.1825700e-03,  6.4867553e-03, -1.0720001e-02, ...,
         -1.7280405e-02,  2.8972510e-02,  9.9825654e-03],
        [-1.5755078e-02,  2.2465093e-03,  2.0973089e-04, ...,
         -5.6080190e-03,  3.1050270e-02, -3.2239787e-02]], dtype=float32)>,
 <tf.Variable 'dense_12/bias:0' shape=(500,) dtype=float32, numpy=
 array([-2.71144114e-03,  2.01431699e-02,  2.42850482e-02, -7.66538782e-03,
         1.16671631e-02,  7.9010

In [24]:
# from keras.models import Model
# intermediate_layer_model = Model(inputs=model.input,
#                                  outputs=model.get_layer('dense_12').output)
# intermediate_output = intermediate_layer_model.predict(data_list[0].iloc[:,:-1].values)
# print(intermediate_output)

[[593920.25      0.        0.   ...      0.        0.        0.  ]
 [     0.        0.        0.   ... 935340.        0.        0.  ]
 [593920.25      0.        0.   ...      0.        0.        0.  ]
 ...
 [ 96492.72      0.        0.   ...      0.        0.   644715.44]
 [ 96492.72      0.        0.   ...      0.        0.   644715.44]
 [ 96492.72      0.        0.   ...      0.        0.   644715.44]]


In [25]:
X_train = pd.read_csv('/content/drive/MyDrive/WR2 Brrr/Trainingsdaten_Proj3/training_dataset_ver5.csv', header = None).iloc[:,:-1].values.astype('int32')
model.predict(X_train)

ValueError: ignored