Dieses Notebook dient dazu, ein trainiertes Netz auf die Testbiler 1-3 anzuwenden und deren Teilgebietskanten zu klassifizieren.

In [1]:
import numpy as np
import pandas as pd
import tensorflow as tf
import os

Zuerst wird das bereits trainierte Netz geladen:

In [2]:
model = tf.keras.models.load_model(os.path.join(os.getcwd(), "/resources/trained_models/trained_model1"))

OSError: SavedModel file does not exist at: C:/resources/trained_models/trained_model1/{saved_model.pbtxt|saved_model.pb}

Daraufhin werden die Daten zu den Testbildern 1-3 eingelesen:

In [ ]:
data_list = []

for i in range(3):
  data_list.append(pd.read_csv(os.path.join(os.getcwd(),"/resources/test_data/test_data") + str(i+1) + '_dump.csv', header = None))
  print(data_list[i].shape)

Anschließend werden die Kanten der Testbilder von dem trainierten Netz klassifiziert:

In [ ]:
i = 2 # Auswahl: Testbild 0, 1, 2
threshold = 0.5 # Schwelle, ab wann ein label als 1 gewaehlt werden soll

X = data_list[i].iloc[:,:-1].values.astype('float32') # Eingabe fuer das Neuronale Netz
y_true = data_list[i].iloc[:,-1].values.astype('float32') # Korrekte labels

# Vorhersage des Modells
y_pred = model.predict(X)
print(y_pred)
# Klassifiziere die Vorhersage -> label 0 oder 1
y_pred_rounded = np.array([1 if prob > threshold else 0 for prob in y_pred]).astype('int64')
print(y_pred_rounded)

# Speichere vorhergesagte labels
file_name = os.path.join(os.getcwd(),"/resources/test_data/predicted_labels_") + str(i+1) + '.csv'
np.savetxt(file_name, y_pred_rounded, delimiter=",")

[[1.8672150e-01]
 [5.1451325e-03]
 [2.8771162e-04]
 [4.0692687e-03]
 [1.0229587e-08]
 [2.7998835e-02]
 [9.5744133e-01]
 [3.1230721e-07]
 [2.5047332e-02]
 [2.0135868e-01]
 [5.0468498e-05]
 [1.5516873e-05]
 [1.5950285e-05]
 [1.5824364e-05]
 [2.1352172e-03]
 [3.1185150e-04]
 [3.3435225e-04]
 [2.6088065e-01]
 [6.3386135e-05]
 [1.5815771e-06]
 [4.2555026e-09]
 [5.5776150e-06]
 [5.9885085e-03]
 [3.1259954e-03]]
[0 0 0 0 0 0 1 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0 0]


In [ ]:
print(y_true)

[0. 0. 0. 0. 0. 0. 1. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]


Abschließend wird die Vorhersage des Modells anhand verschiedener Metriken überprüft: 

In [ ]:
results = model.evaluate(X,y_true)

1/1 [==============================] - 0s 46ms/step - loss: 0.0355 - ACCURACY0.5: 1.0000 - ACCURACY0.4: 1.0000 - ACCURACY0.3: 1.0000 - RECALL0.5: 1.0000 - RECALL0.4: 1.0000 - RECALL0.3: 1.0000 - FN0.5: 0.0000e+00 - FN0.4: 0.0000e+00 - FN0.3: 0.0000e+00 - FP0.5: 0.0000e+00 - FP0.4: 0.0000e+00 - FP0.3: 0.0000e+00 - MAE: 0.0319


Folgende Metriken werden dabei verwendet:

In [ ]:
model.metrics_names

['loss',
 'ACCURACY0.5',
 'ACCURACY0.4',
 'ACCURACY0.3',
 'RECALL0.5',
 'RECALL0.4',
 'RECALL0.3',
 'FN0.5',
 'FN0.4',
 'FN0.3',
 'FP0.5',
 'FP0.4',
 'FP0.3',
 'MAE']